# Generated by Django 3.0.5 on 2020-04-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='feeling',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='감정도'),
        ),
    ]
