# Generated by Django 3.0.5 on 2020-04-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20200427_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='qna',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='질문?'),
        ),
    ]
