# Generated by Django 3.0.5 on 2020-05-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_diary_qna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='feeling',
        ),
        migrations.AddField(
            model_name='diary',
            name='anger',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='분노'),
        ),
        migrations.AddField(
            model_name='diary',
            name='happiness',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='행복'),
        ),
        migrations.AddField(
            model_name='diary',
            name='neatrality',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='중립'),
        ),
        migrations.AddField(
            model_name='diary',
            name='sadness',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='슬픔'),
        ),
        migrations.AddField(
            model_name='diary',
            name='worry',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='걱정'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='qna',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='질문'),
        ),
    ]
