# Generated by Django 2.2.10 on 2020-07-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20200506_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='neatrality',
            new_name='neutrality',
        ),
    ]
